### ISSUE TITLE
SSE Project links

### ISSUE THREAD

**Issue by NamegaH** [75SOFware/75SOFware#1]
https://takmaps.com/wp-content/uploads/ATAK_SSE-Tool-User-Guide-1.0.pdf
https://takmaps.com/wp-content/uploads/ATAK-Plugin-ssetool-1.0-87fb917a-4.3.1-mil-release.apk

**Comment by gorhack** [comment]
https://github.com/75SOFware/75SOFware/commit/a475ea49632015faeff9882ec0fba92cbfb4ca60
