### ISSUE TITLE
Phone landscape show two link button columns

### ISSUE THREAD

**Issue by gorhack** [75SOFware/75SOFware#7]
In iOS Safari, when going to landscape mode it should display the link buttons in two columns (currently stays a single column for both portrait and landscape. Fix the `@media` query in `index.css`.

Related: [1](https://stackoverflow.com/questions/58087446/all-media-queries-for-iphone-12-pro-max-mini-and-older-iphones), [2](https://stackoverflow.com/questions/37136776/viewport-device-width-incorrect-width-large-font-in-safari-landscape-correct)

**Comment by mojo9492** [comment]
see #12
